#!/bin/bash
 
## -- Acme setup
FONT="IBM Plex Mono Text:pixelsize=13:antialias=true"
 
## -- 3270 setup
#FONT="xft:IBM 3270:pixelsize=14:antialias=true"
#FONT="xft:IBM 3270:size=13:antialias=true"
 
/usr/local/bin/stgb -g 130x40 -f "$FONT" -t xterm-265color  -n Ispf -e lspf "${@}" &
