#!/bin/bash

# default font size is 12, can be overriden on command invocation 
FONTSIZE=${1:-12}

#FONT="xft:IBM Plex Mono Text:pixelsize=$FONTSIZE:antialias=true"
#FONT="xft:IBM 3270:size=$FONTSIZE:antialias=false"
FONT="xft:Terminus:size=$FONTSIZE:antialias=false"
#FONT="xft:Anonymous Pro:size=$FONTSIZE:antialias=false"
#FONT="xft:DejaVu Sans Mono:size=$FONTSIZE:antialias=true"
GEOMETRY="90x30"
FLOOR=1
RANGE=5
number=0
while [ "$number" -lt $FLOOR ]
do
  number=$RANDOM
  let "number %= $RANGE"
done
case $number in
    1)
       color="-fg white -bg #696969 -cr white"
       ;;
    2)
       color="-fg SpringGreen -bg #696969 -cr white"
       ;;
    3)
       color="-fg green -bg black -cr white"
       ;;
    4)
       color="-fg black -bg #ffffe5 -cr black"
       ;;
esac
exec /usr/local/bin/xterm -geometry "$GEOMETRY" -fa "$FONT" -title "Xterm" -ls +sb +bc -b 2 -w 0 $color &
